# Generated by Django 4.1 on 2022-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
